# Generated by Django 6.0.2 on 2026-04-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infamodelprofile',
            name='gallery_image_1_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='infamodelprofile',
            name='gallery_image_2_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='infamodelprofile',
            name='gallery_image_3_url',
            field=models.URLField(blank=True),
        ),
    ]
